---
title: Diagrama de clases - SIRDEPA
---
classDiagram
    direction LR
    class Embarcacion {
        +String matricula
        +String nombre
        +TipoEmbarcacion tipo
        +float capacidadBodega
        +EstadoEmbarcacion estado
        +registrarCaptura() Captura
        +enviarPosicionGPS() MonitoreoGPS
        +consultarEstado() EstadoEmbarcacion
    }
    class Pescador {
        +String documento
        +String nombre
        +String comunidad
    }
    class Captura {
        +DateTime fechaHora
        +String zonaPesca
        +float temperaturaAgua
        +float totalKg
        +registrarDatos()
        +generarCodigoQR() Lote
        +validarCumplimiento() bool
    }
    class DetalleCaptura {
        +float cantidadKg
        +int cantidadUnidades
        +float tallaPromedioCm
        +bool cumpleTallaMinima
        +validarTalla() bool
        +calcularTotal() float
        +verificarCuota() bool
    }
    class Especie {
        +String nombreComun
        +String nombreCientifico
        +float tallaMinimaCm
        +float cuotaAnualTn
        +verificarVeda(fecha) bool
        +consultarCuota() float
        +obtenerTallaMinima() float
    }
    class MonitoreoGPS {
        +DateTime fechaHora
        +float latitud
        +float longitud
        +bool enZonaPermitida
        +capturarPosicion()
        +validarZona() bool
    }
    class Alerta {
        +TipoAlerta tipoAlerta
        +String descripcion
        +DateTime fechaHora
        +NivelGravedad nivelGravedad
        +EstadoAtencion estadoAtencion
        +generarAlerta()
        +notificarInspectores()
    }
    class Lote {
        +UUID codigoQR
        +EstadoLote estadoTrazabilidad
        +verificarOrigen() bool
    }
    class Permiso {
        +String tipoPermiso
        +Date fechaInicio
        +Date fechaFin
        +estaVigente(fecha) bool
    }

    Pescador "1" --> "0..*" Embarcacion : posee
    Embarcacion "1" *-- "0..*" Captura : captura
    Embarcacion "1" *-- "0..*" MonitoreoGPS : monitoreoGPS
    Embarcacion "1" --> "1..*" Permiso : tiene
    Captura "1" *-- "1..*" DetalleCaptura : detalleCaptura
    DetalleCaptura "0..*" --> "1" Especie : especie
    MonitoreoGPS "1" --> "0..1" Alerta : alerta
    Captura "0..*" --> "0..1" Lote : pertenece
    Permiso "0..*" --> "1..*" Especie : autoriza
